dateModified: 1750934931
email:
  fromEmail: paul@advantagelearn.com
  fromName: 'Advantage Learn Foundation'
  replyToEmail: null
  template: null
  transportSettings:
    command: '/usr/sbin/sendmail -bs'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    0a3f48ec-0255-4546-962c-d19d581c192e: '4. Reach and Impact Band' # 4. Reach and Impact Band
    0a6e7a59-a78b-45ff-895e-472427126846: Styling # Styling
    0cabfdf7-3657-4649-aac3-7c826b0a027d: Question # Question
    1ee655fc-8a9b-4899-b282-ac3480a05a46: 'Craft Boilerplate' # Craft Boilerplate
    2b290ffb-2f6a-4f61-a700-3237c7c09b37: '1. Hero Band' # 1. Hero Band
    2da9b1ef-d833-4d5c-af58-dfc453824f10: '7. Partner With Us Band' # 7. Partner With Us Band
    2ef70885-9a61-4132-b9c7-c7599db82436: 'Program Name' # Program Name
    4abdfc35-a861-4632-9e81-b3c8983e5afe: 'Person Title' # Person Title
    4b2794b3-5803-43bf-957c-100528311028: '8. How Can We Partner' # 8. How Can We Partner
    4d70caad-a88c-48cf-a48a-1f34eb8a70e8: 'Org Name' # Org Name
    5fd11979-3003-48ce-94f9-65dcebb4a98a: 'Image Text Alternative' # Image Text Alternative
    6a0ad08e-3c64-45de-b9c7-6778988794a8: Stats # Stats
    6a2f84be-0aa8-436d-9647-8716eb634c37: 'How can we partner Image' # How can we partner Image
    6b01ab0f-5e1e-459b-aa6a-951def457885: 'Title Text' # Title Text
    6d4e8119-ad85-408d-8727-e0195dd495bd: 'Org Description' # Org Description
    7b9504f3-0f44-4d8d-9157-366073044e9d: 'How Can We Partner' # How Can We Partner
    7c3dc0e3-d5dc-4bb2-aa73-2a9210c8d82e: Quote # Quote
    8d945038-12f0-4434-be16-282c0d4db6d4: 'Success Stories' # Success Stories
    8edeffe5-5b7c-46e5-8b93-96ff14ab5356: '3. What We Do Band' # 3. What We Do Band
    9c6073a8-c901-4325-b199-2af389c8e856: Organisations # Organisations
    9d1fb737-435c-4b0e-978b-ef8951ee24e7: 'Subtitle Text' # Subtitle Text
    9d395b8d-3002-4765-9a2b-45acea5d761d: 'How Can We Partner Subtitle' # How Can We Partner Subtitle
    9d865bb3-3423-480b-90f2-9b6e0709a24d: 'Step One Heading' # Step One Heading
    19dddbad-59d7-4efd-ac2e-b7d71deb7c5f: 'What We Do' # What We Do
    20dcde3b-f1f4-4244-80ed-5e6b92e80af5: 'Number Two' # Number Two
    20e0895a-d2db-409c-b381-c86b971aaef5: '5. Organisations We Work With Band' # 5. Organisations We Work With Band
    21f106b8-83b2-4648-9e70-94adc36fab96: 'FS List' # FS List
    33a9d2db-de4a-4554-a52e-59fcb6451fc7: SEO # SEO
    36eb7dad-c8a7-495f-b53a-55436cf4ad7e: 'Partnership Background Mobile' # Partnership Background Mobile
    39fc3bc3-0e20-493f-b211-015793be3407: '6. Success Stories Band' # 6. Success Stories Band
    40b24328-3a03-44e5-a870-8aa27d793326: '7. Partner With Us Band' # 7. Partner With Us Band
    42bc02db-d062-47ff-90fb-fa5e8fa1053f: 'Reach Stats' # Reach Stats
    58c77281-8d57-48cf-9aaa-31db51866672: Base # Base
    59f6d049-aaa6-43aa-8bae-aac827ab1997: '2. Who We Are Band' # 2. Who We Are Band
    67f41e09-e046-48b2-8922-8f5c03bbb14c: 'Alf Public' # Alf Public
    83f5e3ec-a5d6-43e3-88c6-d95e61b3287a: '6. Success Stories Band' # 6. Success Stories Band
    258bd81c-4519-4b01-9641-5ac9866ae82a: 'What We Do Items' # What We Do Items
    267cceaa-0983-4f7e-aecf-569f20454f62: 'Link to Site' # Link to Site
    538b9dfc-eb73-4e50-8c2b-835f23ed08f6: 'Number Three Subtitle' # Number Three Subtitle
    650ffca7-ea95-4539-974c-a9436bdfb27c: 'Get Involved Content' # Get Involved Content
    749acd1b-2bbc-4e85-9132-3842c0b12e06: 'Programme Image' # Programme Image
    1313d51f-0848-4d33-9ef3-8e819c980387: 'Body Text' # Body Text
    1711f46b-9498-472d-a284-fdbf153b8ebf: 'Funders Image' # Funders Image
    5331f35f-a9ac-40ff-bd91-532055011591: Testimonial # Testimonial
    5475acc4-915c-4f9e-8d48-add166fb9b81: 'Step Two Heading' # Step Two Heading
    5774a589-ac29-46cb-a6c1-011a802439af: 'Button Text' # Button Text
    7178d9a4-c778-43ea-9e73-d699d694779e: 'Secondary Heading' # Secondary Heading
    7829ab32-990e-4eb3-a6c9-5519032a584a: Common # Common
    9253e245-ca04-4fda-b4e9-9f4a8194a056: 'Mobile Styling' # Mobile Styling
    68116bc0-f420-42c7-9cee-7740a857e692: 'FS Courses' # FS Courses
    73201f5f-19bf-4b82-9bfa-132e7058c223: Testimonials # Testimonials
    95981f25-0b70-4493-ac73-8b35763c9cc1: 'How Can We Partner Title' # How Can We Partner Title
    165558ee-a0fa-4f3b-8b76-b1b78382c20c: Org # Org
    214101f9-132f-47de-90c5-bfa9338638ca: Partnerships # Partnerships
    919847da-318b-45ec-bed8-97615299d97a: '4. Reach and Impact Band' # 4. Reach and Impact Band
    7464326a-3bff-483f-85b0-8215b17436fc: 'Modal Image' # Modal Image
    7955370d-671d-4fd3-9ddf-b3ffa06ecdf7: 'Course Image' # Course Image
    9535810e-7f85-4814-b848-16f889e7477f: 'CTA List' # CTA List
    16396281-07b7-4f70-a562-23c670112d08: 'Person Name' # Person Name
    63298583-683f-4180-b33a-e00d84c8b2d0: Image # Image
    a1d35375-fad3-43fb-a1ed-44da484a56e9: Images # Images
    a457d7c8-f662-4a2b-9a8d-37f3f94263a1: 'Program Price' # Program Price
    a28151a3-58ee-40e0-8035-74233b471d46: Questions # Questions
    b1ccfcfc-10bd-4989-ae3b-dc533efffc74: 'Item Content' # Item Content
    b66ce59e-0812-4eef-ab9d-2fa8e27dae56: Items # Items
    b83dcc20-d894-4cd0-a532-b25220f12946: '8. How Can We Partner' # 8. How Can We Partner
    bd76b64f-5737-455e-9063-f9d5fae094d3: 'Number Four Subtitle' # Number Four Subtitle
    bff79e3c-2368-4e48-8131-33cd7ae0168a: 'Org Image' # Org Image
    c028f2c9-1328-4db9-8982-5c2cdd412695: 'Programme List' # Programme List
    c26c64e2-5c2e-4e97-a28d-b91c7bc182b3: 'number Two Subtitle' # number Two Subtitle
    c74b138e-5657-426c-b60b-c7f308b54df4: 'Footer Image' # Footer Image
    c76a426d-de2d-4a20-ab2f-19211fe897e9: 'Testimonial Image' # Testimonial Image
    c78f633a-5c30-46cc-8263-1253270de97a: Base # Base
    c514881b-8cba-4ba9-8eda-bafe5e03ead3: 'Course Name' # Course Name
    c1290708-9c46-4cb3-85ba-c6541921e469: 'Partnership Background' # Partnership Background
    cd941a9e-524d-4a66-9e4b-b431128c00ab: 'Item Image' # Item Image
    d2d28287-fcee-4423-b368-21bf61e75978: 'Reach And Impact' # Reach And Impact
    d37ac34e-151f-458a-b6f7-337227fa23c4: 'Number Four Title' # Number Four Title
    da521a95-5e2f-4d91-ace3-83aa770156bd: 'Stat Description' # Stat Description
    dabf01f8-6179-4010-9a41-2744be70d508: 'Public Schema' # Public Schema
    dbb59129-1e74-45d8-bff0-91adda24e2d6: Programmes # Programmes
    dbe5b2c4-ebe7-47e1-8052-b3bb9d2ff0df: 'Stat Number' # Stat Number
    e0ba8e8e-433f-412c-ba85-989fd3c1de95: 'Number Three' # Number Three
    e0da9c8b-7340-4e05-81ba-6c6b1e03d853: 'Stat Image' # Stat Image
    e04fcab5-62e3-493a-9698-b4a2aa21cc9f: 'Funders Content' # Funders Content
    e6d6f23c-0f24-45a8-b2cc-25b4db286154: 'Item Heading' # Item Heading
    e7a2455c-7aa3-4cc4-ab7d-244c210567f8: 'Number One' # Number One
    e9dba679-88fc-43a6-a9c2-b85286ee8d06: '5. Organisations We Work With Band' # 5. Organisations We Work With Band
    e703c114-2dd3-4a46-bac2-c72e92cc8afd: '2. Who We Are Band' # 2. Who We Are Band
    ed472fd5-7d72-4ee5-af6a-1b4bafde337e: 'Question Image' # Question Image
    ee614a99-88a5-404c-837b-345aa6e9a425: 'Number Four' # Number Four
    eeb2fa43-5fae-4937-b3fc-043bf7ce2758: Logo # Logo
    f0827ba4-f970-4ab3-880e-7e742fc58848: 'Programme Subtitle' # Programme Subtitle
    f091b36d-7d39-4184-a7cf-03d6e11da7c8: 'Button Link' # Button Link
    f4ea8fc1-113a-47f3-bfa4-e207d5756f53: 'Further Discount' # Further Discount
    f5dad74b-73d6-4dd9-a4d2-6385968a7209: Base # Base
    f7a4da3f-b25f-4786-9651-3a055d3390b3: 'Mobile Image' # Mobile Image
    f50e3fdf-4d4a-4023-8108-532bc6d15e7a: 'Number Three Title' # Number Three Title
    f535a17d-4928-4c39-9870-1dc99a10d689: '1. Hero Band' # 1. Hero Band
    f4860a69-f49f-4207-a5a5-455f0c60e75a: 'Item Type' # Item Type
    f9571570-8238-44c9-a636-8b255b835ef6: '3. What We Do Band' # 3. What We Do Band
    fea1e2b7-40e2-4f91-9032-82136bbe0309: 'Organisation Info' # Organisation Info
plugins:
  aws-s3:
    edition: standard
    enabled: true
    schemaVersion: '1.2'
  freeform:
    edition: pro
    enabled: true
    licenseKey: DFZ7PF4HQ68ICGUDOEW23CFJ
    schemaVersion: 3.6.5
    settings:
      ajaxByDefault: true
      alertNotificationRecipients: ''
      autoScroll: true
      autoScrollToErrors: true
      badgeType: all
      blockedEmails: null
      blockedEmailsError: 'Invalid Email Address'
      blockedIpAddresses: null
      blockedKeywords: null
      blockedKeywordsError: 'Invalid Entry Data'
      bypassSpamCheckOnLoggedInUsers: false
      clientDigestFrequency: 1
      clientDigestRecipients: ''
      customErrorMessage: null
      customHoneypotName: null
      defaultTemplates: true
      defaultView: dashboard
      digestFrequency: 1
      digestOnlyOnProduction: false
      digestRecipients: ''
      displayFeed: true
      emailTemplateDirectory: null
      emailTemplateStorage: db
      exportLabels: false
      fieldDisplayOrder: name
      fillWithGet: false
      footerScripts: false
      formFieldShowOnlyAllowedForms: false
      formSubmitDisable: true
      formSubmitExpiration: null
      formTemplateDirectory: embeds/forms
      formattingTemplate: flexbox.html
      freeformHoneypot: true
      freeformHoneypotEnhancement: false
      hideBannerDemo: false
      hideBannerOldFreeform: false
      minimumSubmitTime: null
      pluginName: ''
      purgableSpamAgeInDays: null
      purgableSubmissionAgeInDays: null
      purgableUnfinalizedAssetAgeInMinutes: 180
      recaptchaBehaviour: display_error
      recaptchaEnabled: false
      recaptchaErrorMessage: 'Please verify that you are not a robot.'
      recaptchaKey: null
      recaptchaLazyLoad: false
      recaptchaMinScore: 0.5
      recaptchaSecret: null
      recaptchaSize: normal
      recaptchaTheme: light
      recaptchaType: v2_checkbox
      rememberPageSubmitOrder: true
      removeNewlines: false
      renderFormHtmlInCpViews: true
      salesforce_client_id: null
      salesforce_client_secret: null
      salesforce_password: null
      salesforce_username: null
      saveFormSessionLimit: 10
      saveFormTtl: 30
      scriptInsertLocation: footer
      scriptInsertType: pointers
      sessionContext: payload
      sessionContextCount: 100
      sessionContextSecret: ''
      sessionContextTimeToLiveMinutes: 180
      sessionEntryMaxCount: 50
      sessionEntryTTL: 10800
      showErrorsForBlockedEmails: false
      showErrorsForBlockedKeywords: false
      showTutorial: true
      spamFolderEnabled: true
      spamProtectionBehaviour: simulate_success
      submissionThrottlingCount: null
      submissionThrottlingTimeFrame: null
      successTemplateDirectory: null
      twigInHtml: true
      twigInHtmlIsolatedMode: true
      updateSearchIndexes: true
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  seo:
    edition: standard
    enabled: true
    schemaVersion: 3.2.0
    settings:
      description: ''
      facebookAppId: ''
      metaTemplate: seo-meta.twig
      removeAlternateUrls: ''
      robots:
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
      robotsTxt: "{# Sitemap URL #}\r\nSitemap: {{ url(seo.sitemapName ~ '.xml') }}\r\n\r\n{# Disallows #}\r\n{% if craft.app.config.env != 'production' %}\r\n\r\n{# Disallow access to everything when NOT in production #}\r\nUser-agent: *\r\nDisallow: /\r\n\r\n{% else %}\r\n\r\n{# Disallow access to cpresources/ when live #}\r\nUser-agent: *\r\nDisallow: /cpresources/\r\n\r\n{% endif %}"
      sitemapLimit: '1000'
      sitemapName: sitemap
      socialImage:
        - '304'
      title:
        -
          __assoc__:
            -
              - key
              - '1'
            -
              - locked
              - '0'
            -
              - template
              - '{title}'
        -
          __assoc__:
            -
              - key
              - '2'
            -
              - locked
              - '1'
            -
              - template
              - ' - {{ siteName }}'
      titleSuffix: null
      twitterHandle: ''
system:
  edition: solo
  live: true
  name: 'Advantage Learn Foundation'
  retryDuration: null
  schemaVersion: 3.8.0.1
  timeZone: Africa/Johannesburg
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
